# TEMPORARY FILE: EDITS WILL NOT BE SAVED!
# This file was generated by omfit_classes.utils_base.function_to_tree()

defaultVars(kw={})
self = 

"""
Plots important variables related to ELM detection

:return: (Figure instance, array of Axes instances)
"""
method = self['settings']['detection'].get('detection_method', 0)
method = self.check_detection_inputs(method)
if method == 0:
    f, ax = self.classic_elm_detection_plot(**kw)
elif method == 1:
    f, ax = self.jump_and_hold_elm_detection_plot(**kw)
else:
    raise ValueError('Unrecognized ELM detection method: {}\nValid options are: [0, 1]'.format(method))